name: Update GitHub Data

on:
  schedule:
    - cron: "17 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run script
        run: node scripts/update-github-data.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/github-data.json

          git diff --staged --quiet || git commit -m "Update GitHub data"

          git push